// ABOUTME: Defines standardized error codes used across all tools in this MCP server.
// ABOUTME: Keeps structuredContent.error values consistent for clients and AI agents.

export enum ErrorCode {
	NOT_FOUND = "NOT_FOUND",
	OUTSIDE_WORKSPACE = "OUTSIDE_WORKSPACE",
	SENSITIVE_PATH = "SENSITIVE_PATH",
	FILE_IGNORED = "FILE_IGNORED",
	PATH_IGNORED_BY_POLICY = "PATH_IGNORED_BY_POLICY",
	PATH_IS_NOT_A_DIRECTORY = "PATH_IS_NOT_A_DIRECTORY",
	FILE_TOO_LARGE = "FILE_TOO_LARGE",
	INVALID_REGEX = "INVALID_REGEX",
	EDIT_NO_CHANGE = "EDIT_NO_CHANGE",
	EDIT_FILE_EXISTS = "EDIT_FILE_EXISTS",
	EDIT_NO_OCCURRENCE_FOUND = "EDIT_NO_OCCURRENCE_FOUND",
	EDIT_EXPECTED_OCCURRENCE_MISMATCH = "EDIT_EXPECTED_OCCURRENCE_MISMATCH",
	OVERWRITE_DISABLED = "OVERWRITE_DISABLED",
	PERMISSION_DENIED = "PERMISSION_DENIED",
	DISK_FULL = "DISK_FULL",
	IS_DIRECTORY = "IS_DIRECTORY",
	PARENT_NOT_DIRECTORY = "PARENT_NOT_DIRECTORY",
	WRITE_FAILED = "WRITE_FAILED",
}
